### ISSUE TITLE
Problema descripcionContiene

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#1]
estaba realizando la funcion filtrar gasto de la unica manera que he sido capaz de que me pase los test, pero hasta que he llegado a descripcionContiene, una vez he llegado aquí no consigo que me pase el test.

**Comment by pedroprieto** [comment]
Tienes que nombrarme con `@pedroprieto` para que me llegue la notificación.

Imagino que esto ya lo tienes resuelto :wink:
