### ISSUE TITLE
Borrar Etiquetas

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#10]
@pedroprieto No consigo que me pase el test final de borrar etiquetas.

He probado de todo, usar split, pusar .gasto sin .gasto. En la funcion dentro del bucle he probado también de todo y no se que detalle me falte, creo que he probado todo lo posible y que se me ha ocurrido, pero ni por suerte he conseguido dar con la tecla. Tengo ambas partes mal? la función consstructuro y el botón del span o solo una de las dos? También he mirado a través de la consola del navegador, pero no aparece nada esta vez.

**Comment by pedroprieto** [comment]
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/fa2325df1c18166f201489f004fda15f2cfab894/js/gestionPresupuestoWeb.js#L40

Tienes que pasar también la etiqueta como propiedad del objeto. Igual que pasas el `gasto`, tienes que pasar la `etiqueta`.

Y luego, en la función manejadora:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/fa2325df1c18166f201489f004fda15f2cfab894/js/gestionPresupuestoWeb.js#L156

Tienes que hacer referencia al parámetro `this.etiqueta`, que es la que quieres borrar. Tal como estás haciendo estás tratando de borrar todas las del gasto. Y encima no le pasas bien el parámetro, porque le pasas un array, no una lista.

Un saludo!

**Comment by HiginioUrbano** [comment]
Si, si esas cosas las habia probado ya, pero no me iban igualmente, te
habia hecho el push con lo ultimo que habia probado, te actualizo con un
issue y me dices donde estoy fallando.

**Comment by pedroprieto** [comment]
Reviso el otro issue.
