### ISSUE TITLE
Actualizo el codigo

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#11]
@pedroprieto Aqui tienes el codigo que tenía más parecido a lo que tu me decías, pero me seguía sin funcionar

**Comment by pedroprieto** [comment]
![imagen](https://user-images.githubusercontent.com/7632447/141440643-94ceb8a6-519a-415e-b062-afd8138b5306.png)

El error de ejecución. ¿Por qué pasa?

**Comment by HiginioUrbano** [comment]
Eso te lo suele poner cuando no has declarado la variable con let/var. Es posible que sea porque yo en el codigo gestionPresupuesto lo tenga definido como this.etiquetas con S, pero es que con S tampoco me funciona. Si no es por eso, entonces no lo se. Como te digo, con S tampoco me funcionaba.

**Comment by pedroprieto** [comment]
No. Es que no encuentra la propiedad `etiqueta` definida en el objeto. Efectivamente, aquí compruebas que has definido `.etiquetas`, no `etiqueta`:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/613f369c37544d4691708a612d451ca8adfae91e/js/gestionPresupuestoWeb.js#L41

Prueba. Verás que avanzas y que aparece otro error :wink: A ver si puedes con él.

**Comment by HiginioUrbano** [comment]
Hecho, era hacer eso, quitar gasto para que fuese iterable y listo, ya te hago el pull request

**Comment by pedroprieto** [comment]
:+1:
