### ISSUE TITLE
Error getElementById

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#12]
@pedroprieto Buenas, no para de decirme cuando pulso el botón para comprobar que se crea el formulario que getElementById is not a function. He probado 2000 cosas distintas y siempre me da el mismo error y no se qué estoy haciendo mal.

**Comment by pedroprieto** [comment]
Por favor, dime en qué línea se produce el error.

**Comment by HiginioUrbano** [comment]
He agregado líneas mientras esperaba en mi código y no lo sé 100% seguro,
pero si mi memoria no me falla, en el código que tu tienes es la 227-228

**Comment by pedroprieto** [comment]
Puedes indicar la línea copiando y pegando el enlace. Para ello tienes que copiar el link (imagen a continuación) y pegarlo en el comentario en GitHub:
![linea_github](https://user-images.githubusercontent.com/7632447/142236386-1fba6e07-1a0f-4a02-b56b-65470278a3b7.gif)

Supongo que la línea es esta:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/9758c8fa7cdf849c3b518e7a951aefa5f4ba6f46/js/gestionPresupuestoWeb.js#L224

Y efectivamente, no es una función... la función acaba en `d` minúscula :wink:

**Comment by HiginioUrbano** [comment]
Tengo en cuenta lo del remarcar.

No me puedo creer que esté cometiendo errores tan tontos últimamente.
Revisé el código fácilmente durante una hora letra por letra y no fui capaz
de verlo.

**Comment by pedroprieto** [comment]
Cosas que pasan... Paciencia pues!!
