### ISSUE TITLE
Problema en la funcion filtrarGastoWeb

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#13]
Buenas @pedroprieto estaba realizando la función filtrar gastoWeb y me he atascado, puesto que tengo un error, pero con los datos que me da el cypress y tal no consigo saber en qué lugar tengo exactamente el error, me podrías echar un cable?

**Comment by HiginioUrbano** [comment]
He actualizado el código agregando un limpiador como hago en la función repintar para vaciar la lista que ya estaba agregada de forma predefinida. Me ha costado verlo puesto que la función en la guía no lo requería, pero casualmente en siempre era el doble y lo he visto, pero me sigue sin pasar el test de manera completa, se me para a mitad, concretamente en la parte que comprueba las descripciones, pero no se porque.

**Comment by HiginioUrbano** [comment]
@pedroprieto la reabro que la habia cerrado sin querer

**Comment by pedroprieto** [comment]
Buenas,

Ábrelo en el navegador y mira la consola a ver si hay algún error. Envíame captura.

**Comment by HiginioUrbano** [comment]
He vuelto a actualizar el código, solucionando lo de las descripciones, ahora el error parece estar en las etiquetas.

![image](https://user-images.githubusercontent.com/85572405/143029377-d8ff28b2-2441-4b70-8dc0-6ef54eb875e7.png)

**Comment by HiginioUrbano** [comment]
Te adjunto la captura de pantalla

**Comment by HiginioUrbano** [comment]
Sigo dándole vueltas al código, he detectado el error, está a la hora de filtrar las etiquetas, me quedo con 2 y debería quedarme con 3, pero nada lo que he probado soluciona el problema y estoy desesperado ya :(

**Comment by pedroprieto** [comment]
Buenas,

https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/a5b4b61b351d75dfb0160b34ac3acf89cd1834e3/js/generarDatosEstaticos.js#L18

El gasto que creas aquí tiene la etiqueta `Transporte` y no `transporte`. Como la búsqueda distingue mayúsculas de minúsculas, no devuelve ese gasto en el filtrado.

Fallo difícil de pillar... :wink: 

Un saludo!!

**Comment by pedroprieto** [comment]
Igual sería buena idea modificar la expresión regular para que no distinga mayúsculas de minúsculas... Me lo apunto para el año que viene!!

**Comment by HiginioUrbano** [comment]
Pero en teoría tengo puesto /gi, que la i es lo que se usa para quitar está
distinción, no?

**Comment by pedroprieto** [comment]
Sí, la expresión regular la detecta. Y le pasa a la función de filtrado un array de etiquetas que incluye `Transporte`. Pero el problema no está ahí, sino en la función de filtrado:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/a5b4b61b351d75dfb0160b34ac3acf89cd1834e3/js/gestionPresupuesto.js#L225

Aquí usas un operador de comparación de igualdad, así que los textos tienen que ser iguales. Y `"transporte" != "Transporte"`.

Saludos!

**Comment by HiginioUrbano** [comment]
Y que hago? modificar esa función?

**Comment by HiginioUrbano** [comment]
Y en ese caso, como lo hago? porque solo me queda eso, tengo hasta la práctica de almacenamiento realizada

**Comment by HiginioUrbano** [comment]
He pasado el test primero añadir .toLowerCase en ambos comparadores, pero cuando mete (transporte, casa) me da error también

**Comment by pedroprieto** [comment]
No, no... Cambia el texto de la etiqueta para que ponga `transporte` con minúscula. No te compliques.

**Comment by HiginioUrbano** [comment]
Que lo hago en el archivo de test?

**Comment by HiginioUrbano** [comment]
Y de ser asi, en que archivo de test está ese?

**Comment by pedroprieto** [comment]
No hombre. En tu archivo:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/a5b4b61b351d75dfb0160b34ac3acf89cd1834e3/js/generarDatosEstaticos.js#L18

Ponlo en minúscula, tal como indicaba el enunciado.

**Comment by HiginioUrbano** [comment]
Vale, no me acordaba de esa parte de la práctica ya, cambiado y solucionado
todo, gracias.

**Comment by pedroprieto** [comment]
A mandar! :wink:

**Comment by HiginioUrbano** [comment]
Una última pregunta aprovechando este hilo, de cara al exámen las
expresiones regulares son importantes?

**Comment by pedroprieto** [comment]
No. Puse un mensaje en el foro al respecto. Tienes lo que va a entrar en Aules. Y en el vídeo de la tutoría de esta semana.

Un saludo!

**Comment by HiginioUrbano** [comment]
Lo he visto justo después de preguntarte -.-´
