### ISSUE TITLE
Error cargarGastoAPI

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#14]
@pedroprieto Buenas,

En la línea 401 de mi código, inspeccionando el elemento, me sale que tengo un error de sintaxis en la parte del fetch, pero no entiendo porque, debido a que lo he hecho tal cual aparece en la teoría, qué tengo mal, para que me tire error en la sintaxis?

**Comment by pedroprieto** [comment]
Buenas,

Te falta un detalle: las llamadas a `await` deben hacerse dentro de funciones asíncronas. Lo tienes en la teoría, en los videotutoriales y en las grabaciones de tutoría.

Un saludo!

**Comment by HiginioUrbano** [comment]
Vale! Vi el tutorial de las APIs, pero no había visto que había uno de la
programación asíncrona, ahora ya lo tengo bastante más claro, gracias
