### ISSUE TITLE
Error al cargar gastosAPI

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#15]
Aquí te lo dejo, disculpas, siempre tengo abiertos los dos y me confundí

Muy buenas @pedroprieto (creo) he conseguido hacer funcionar la funcion cargarGastosApi y BorrarGastosApi agregando async antes de la función tal y como indicas en el tutorial. Ahora bien, cuando pulso en el botón borrarGasto, me genera un conflicto entre ambas funciones y no se porqué. La orden se ejecuta, puesto que me borra el gasto en el servidor, pero no se me actualiza automaticamente ya que me salta el conflicto entre ambas, debo pulsar en el botón cargarGastoAPI para ver el resultado, qué estoy haciendo mal=?

**Comment by pedroprieto** [comment]
Buenas,

Los objetos de la API no deben interactuar con los locales, ya que no funcionará. Para borrar un objeto de la API debes haberlo creado en la API. No puedes borrar un objeto con el botón `borrarAPI` si ha sido creado en local.

Dicho esto, ¿por qué tienes comentada esta funcionalidad?
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/24f0923cef3f7f5ad00ed26bb36f78ea8a82ad64/js/gestionPresupuestoWeb.js#L83

Un saludo!

**Comment by HiginioUrbano** [comment]
Buenas, la funcionalidad la tengo comentada para que no me haga conflicto con el resto de cosas puesto que me quedé a mitad de esa parte, en el nuevo código ya lo he hecho.

Pero los objetos que intento borrar están siempre en la API, aún así no se me cargan de manera predeterminada una vez los borro, la función cargarDatos no salta, me da error, en cambio si pulso el botón de cargar sí me funciona y sí me borra el gasto de la API, no se si me estoy explicando bien.

PD: te actualizo el código tal y como lo tengo ahora que ya no tengo comentada la parte que me comentas y a la hora de crear un nuevo gasto se me crea por partes en 8 partes diferentes y tampoco entiendo porque. Muchas gracias

**Comment by HiginioUrbano** [comment]
Y también cuando le doy a editar (formulario) los botones que me aperecen abajo son los de añadir gasto (formulario) y no se porqué he repasado 20 veces el código y no doy con el motivo, seguro que es un error super tonto, pero no veo el motivo por el cual pasa eso, puesto que tengo el botón asociado al evento editarHandle

**Comment by pedroprieto** [comment]
Buenas,

Envíame el usuario que utilizas para la API. Seguramente hayas creado los gastos sin el campo `etiquetas`...

**Comment by HiginioUrbano** [comment]
higiniourbano

No, sí que he usado etiquetas (creo)

**Comment by pedroprieto** [comment]
Sí, está bien.

Error:
![imagen](https://user-images.githubusercontent.com/7632447/149489354-70956f99-1b4e-4861-be47-24a7005298e5.png)

En la línea 318 haces referencia a `gasto`, que no existe. En su lugar, es `this.gasto`.

En cuanto a los botones que aparecen al darle a editar, lo veo correcto... Lo único, no añadas el botón a través de JS: hazlo en la plantilla (`template`) del HTML.

Aún así, tienes más problemas, ya que al corregirlo sigue sin funcionar. Ve poco a poco...

**Comment by HiginioUrbano** [comment]
Vale, pero el problema de que al borrar el gasto, no me carga los gastos?
Ese problema donde está? Porque es el que más loco me tiene

**Comment by HiginioUrbano** [comment]
He actualizado el gasto, ya me crea el gasto correctamente.

Actualmente tengo 2 problemas que no estoy sabiendo solucionar por mi mismo.

1.- Da igual si creo o borro un gasto en la API, no me carga la API excepto que le de al botón de cargargastosAPI, aunque si que me crea o me borra el gasto en la API.

2.- No consigo que al editar me detecte la ID correcta, he probado diferentes combinaciones de this.gasto etc y ninguna me funciona. El funcionamiento es el mismo que en el caso de borrarlo, por qué no me funciona usando la misma sintaxis?

**Comment by pedroprieto** [comment]
Buenas,

El problema es que defines `cargarGastosApi` como una función constructora de un __objeto manejador de eventos__.
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/7564d04744185e58bc9438acec4db9180d7ef0e6/js/gestionPresupuestoWeb.js#L398-L399

El enunciado dice que tienes que crearla como una __función manejadora de eventos__. De esta manera la podrás llamar como una función normal; la que tú has creado no puedes llamarla, ya que lo que hace es crear un objeto.

Un saludo!

**Comment by HiginioUrbano** [comment]
Pero es que si quito lo de this.handleEvent y lo dejo como async function cargarGastosAPI() no me funciona, me tira error en el await

**Comment by pedroprieto** [comment]
Debe funcionar. Lo único, tendrás que cambiar el modo en el que la utilizas como manejadora de eventos:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/7564d04744185e58bc9438acec4db9180d7ef0e6/js/gestionPresupuestoWeb.js#L518-L520

Un saludo!

**Comment by HiginioUrbano** [comment]
Si, lo había cambiado, simplemente se me había olvidado quitar los parentesis de la función, solo había quitado el new, ya funciona!

**Comment by HiginioUrbano** [comment]
Lo único que me queda es que no me reconoce el Id del gasto, he usado el mismo método que para borrarlo y he probado otras cosas, pero no me lo coge

**Comment by HiginioUrbano** [comment]
Buenas Pedro, he vuelto a actualizar el código porque he agregado la práctica de librerías.

El problema que te comento arriba aún no lo he solucionado, el del id en editar, si me pudieses echar un cable te lo agradecería.

Con las librerías creía haberlo hecho todo bien, pero me salta un error: DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.0/dist/chartjs-adapter-moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Esto me dice la consola, es como si el script no lo detectase bien.

**Comment by pedroprieto** [comment]
Buenas,

De momento el error que veo es que no has corregido la función `cargarGastos`, tal como os indiqué en el foro y en el enunciado corregido de la práctica de almacenamiento local:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/df58bec9073d38ad5c23abd38c341b32fc565e88/js/gestionPresupuesto.js#L291

Corrige eso y prueba de nuevo.

Con respecto al problema de las librerías, he ejecutado tu código y no me ha salido ningún error de carga de librerías...

Un saludo!

**Comment by HiginioUrbano** [comment]
Si hago la corrección que me indicas el código de cargarGastosAPI me deja de funcionar.

Y lo que me comentas de las librerías, puede ser que no funcionen en google Chrome? Que es el navegador que yo uso actualmente. Por consiguiente, las librerías las tengo realizadas correctamente?

**Comment by pedroprieto** [comment]
Buenas,

Tienes que hacer las correcciones pero teniendo en cuenta qué parámetro has utilizado en tu función.

Las librerías se cargan, pero las gráficas no se cargan.

No es un tema de navegadores.

Un saludo!

**Comment by HiginioUrbano** [comment]
He rehecho la función teniendo en cuenta como tenía llamado a los gastos en mi programa y he añadido los parámetros. En la función cargarGastosAPI no he tocado nada, pero no me va. Y he hecho la lógica del código tal cual expones  en la corrección y nada.

Entonces de que es un tema? De fallo en el código? Lo he cogido tal cual lo has pasado y también he seguido los pasos tal cual expones en las tutorías y en la práctica.

**Comment by pedroprieto** [comment]
Buenas,

Si no subes el código no puedo ver nada...

**Comment by HiginioUrbano** [comment]
Ya lo tienes, que ayer estuve liado y no pude subirlo

**Comment by pedroprieto** [comment]
Buenas,

![imagen](https://user-images.githubusercontent.com/7632447/149920170-11b61e0b-ae6a-4352-a2ff-9987e36fb49f.png)

![imagen](https://user-images.githubusercontent.com/7632447/149920294-5e950e5b-1bb2-450d-907b-e7c9c1c10929.png)

![imagen](https://user-images.githubusercontent.com/7632447/149920354-2e4040aa-92e4-4e0f-8568-4adfa62c29e6.png)

![imagen](https://user-images.githubusercontent.com/7632447/149920418-e85c060e-4919-461e-86bc-befbb76f1f75.png)

![imagen](https://user-images.githubusercontent.com/7632447/149920479-2f3d8291-1669-4443-84bb-a85aacb3a8a8.png)

Este tipo de errores tienes que buscarlos tú más a fondo. No puedes ponerme un issue cada vez que te salga un fallo... Por favor, trata de tirar un poco del hilo del error y buscar el fallo antes.

Un saludo!

**Comment by HiginioUrbano** [comment]
Pedro, lo inspeccione, pero es que a mí ese fallo no me sale en mi consola. Quiero decir, el fallo existe y es evidente el fallo, pero cuando lo inspeccionaba en mi consola, te prometo que no me sale nada de nada. Solo me sale un aviso en amarillo que dice lo siguiente;:

DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.0/dist/chartjs-adapter-moment.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Este es el único fallo que me salía, por eso te mandé el mensaje

**Comment by pedroprieto** [comment]
¿No te sale en la consola del navegador? Mándame captura para que vea donde lo estás mirando, por si no estás en el sitio correcto...

**Comment by HiginioUrbano** [comment]
![image](https://user-images.githubusercontent.com/85572405/149927885-9f9a9701-a10c-4413-8b7a-fa1aabf2728e.png)

**Comment by pedroprieto** [comment]
Sí, es ahí, pero en la barra lateral accede a `Console` (a la derecha de `Elements`) y prueba a interactuar con la aplicación. Te aparecerán los errores.
![imagen](https://user-images.githubusercontent.com/7632447/149928200-0e064b7b-c8fb-420c-a3a6-c02408ca8048.png)

**Comment by HiginioUrbano** [comment]
Interactuo abajo que es lo mismo en un atajo más pequeñito, no?

Al margen de eso, el error que no consigo solucionar por mucho que pruebe, que si me detecta la consola. Es que al editar no me saca el id del gasto de la API. No entiendo cual es el problema cuando en borrar gasto me lo saca sin ningún tipo de problema, pero en este caso me tira error. No sería lo mismo para sacar la ID del gasto en el caso de borrar que de editar?

**Comment by pedroprieto** [comment]
Porque añades el gasto y el formulario al botón en lugar del manejador:

https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/8b39013fe7f8a6d1a47939a6dafe5f6f19e89b27/js/gestionPresupuestoWeb.js#L367-L370

**Comment by HiginioUrbano** [comment]
Qué error más tonto... Muchas gracias! Ya lo tengo todo, te hago el pull request.
