### ISSUE TITLE
Fallo al intentar las  mejoras

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#16]
Buenas @pedroprieto

He estado intentando las mejoras durante un buen rato esta tarde. He conseguido arreglar el error del test 4, pero no he conseguido arreglar el error del 7 ni del 8 y la verdad es que no he sabido como hacerlo porque me está costando recordar las partes de esa práctica y no consigo encontrar el error ni lo que tenía que conseguir en esa parte.

Por otro lado he estado trabajando en lo que no me corregiste de que apareciese el texto del gasto a editar, tienes comentado para que no entre en conflicto lo que he intentado, me aparece undefined en el cuadro de texto, por lo que he deducido que es porque no tiene acceso al código, pero he intentado darle acceso a los gastos en todo momento, pero no he conseguido que se quite lo de undefined por el valor correcto.

Muchas gracias y un saludo.

**Comment by pedroprieto** [comment]
Buenas,

> Buenas @pedroprieto
> 
> He estado intentando las mejoras durante un buen rato esta tarde. He conseguido arreglar el error del test 4, pero no he conseguido arreglar el error del 7 ni del 8 y la verdad es que no he sabido como hacerlo porque me está costando recordar las partes de esa práctica y no consigo encontrar el error ni lo que tenía que conseguir en esa parte.
> 

![imagen](https://user-images.githubusercontent.com/7632447/150107773-330f9ed8-0bfd-42c1-b9c4-8ff73742b65a.png)

https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/3cb51046698e5d17c680d04eaf77634cfe1ae028/js/generarDatosEstaticos.js#L13


> Por otro lado he estado trabajando en lo que no me corregiste de que apareciese el texto del gasto a editar, tienes comentado para que no entre en conflicto lo que he intentado, me aparece undefined en el cuadro de texto, por lo que he deducido que es porque no tiene acceso al código, pero he intentado darle acceso a los gastos en todo momento, pero no he conseguido que se quite lo de undefined por el valor correcto.

https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/3cb51046698e5d17c680d04eaf77634cfe1ae028/js/gestionPresupuestoWeb.js#L363
`this.descripcion` no existe: existe `this.gasto`.

Un saludo.

**Comment by HiginioUrbano** [comment]
vale, solo me queda el error del test 8 que me dice que almacenamientoGasto no es iterable y no consigo solucionarlo

**Comment by pedroprieto** [comment]
El fallo está aquí:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/3cb51046698e5d17c680d04eaf77634cfe1ae028/js/gestionPresupuestoWeb.js#L452

Si la línea anterior no encuentra la clave, devuelve `null`.

Un saludo!
