### ISSUE TITLE
Error en interaccionHMTL

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#2]

**Comment by pedroprieto** [comment]
@HiginioUrbano ,

Los ficheros `.js` no llevan atributos HTML. Por tanto, estas etiquetas te sobran:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/c19cefae5db5ce46f2574e4ea0d1bd079ebd8c93/js/generarDatosEstaticos.js#L1
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/c19cefae5db5ce46f2574e4ea0d1bd079ebd8c93/js/generarDatosEstaticos.js#L14

Recuerda nombrarme con `@pedroprieto` o no me llegarán las notificaciones.

Un saludo!

**Comment by HiginioUrbano** [comment]
Vale, claro, tiene toda la lógica del mundo.
