### ISSUE TITLE
Error a pasar el test @pedroprieto

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#3]
Buenas @pedroprieto no consigo pasar el primer test, pero ya no sé si es porque estoy cometiendo un error en el código de la funcion en el .js de gestionPresupuestoWeb o sigo sin hacer bien los métodos import, ya que me aparecen en grisaceo, como si no estuviesen siendo usados. Muchas gracias

**Comment by pedroprieto** [comment]
Buenas,

En el fichero `generarDatosEstaticos` tienes que llamar a las funciones correspondientes tal como indica el enunciado aquí: https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/master/enunciados/interaccionHTML.org#fichero-jsgenerardatosestaticosjs

El test comprueba el resultado (que aparezcan en el HTML). Para ello tienes que poner el código correspondiente también en `generarDatosEstaticos`.

Un saludo!!

**Comment by HiginioUrbano** [comment]
He puesto lo /js/gestionPresupuestoWeb.js y sigo teniendo el mismo
problema. O hay que llamarlo si o si mediante import * as? Estoy un poco
cansado de esto porque llevo días sin poder avanzar por esto y se me va a
acumular todo.

**Comment by pedroprieto** [comment]
A ver... Tienes que hacer el `import`, que ya tienes hecho. El `import` es para tener las funciones disponibles en tu script.

Luego, debajo de esta línea:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/f54a0fe573f348fa7cac43aa943f3b241d057088/js/generarDatosEstaticos.js#L13

Tienes que llamar a las funciones que has importado para ejecutar el código. Por ejemplo, para actualizar el presupuesto debes ejecutar:

```js
actualizarPresupuesto(1500);
```

Y así con todo lo que se pide en https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/master/enunciados/interaccionHTML.org#fichero-jsgenerardatosestaticosjs

Un saludo!!

**Comment by HiginioUrbano** [comment]
Vale, muchas gracias, esto estaba siendo mi error. Si la próxima vez
pudieses indicar eso, que yo suelo ir en cascada al hacer los ejercicios
creyendo que hay que hacerlo así, que lo de los test me está despistando un
poco la verdad. Aunque para las próximas estaré más avispado.

**Comment by pedroprieto** [comment]
:+1: 

En el enunciado está indicado el orden correcto para hacerlo. La única diferencia es que en esta práctica los tests no testean funciones independientes, sino el resultado final.

Un saludo!!
