### ISSUE TITLE
Sigue sin pasarme los test

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#4]
@pedroprieto

He mirado tu videotutoria, he hecho de la misma manera las funciones, tengo los import igual y (creo) que el codigo de mostrarDatosId está bien formulado, porque no he parado de mirar tanto en apuntes como por internet y creo que se construye de esa manera. Aún así, no me pasa los test, no se donde puede estar el fallo...

**Comment by pedroprieto** [comment]
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/9043af03b66282cdd85bfbbc9b3dcce334c02e4c/js/generarDatosEstaticos.js#L2

Te falta el `.js` al final...

**Comment by HiginioUrbano** [comment]
Me cago en mi... mil perdones
