### ISSUE TITLE
No se como debo seguir

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#5]
@pedroprieto
Me he quedado aquí bloqueado, porque he realizado la función mostrarGastoWeb siguiendo las cosas que salen en los apuntes y con las cosas que comentas en la tutoría, pero a partir de aquí ya no veo por donde seguir ni que me puede llegar a faltar... Estoy completamente perdido

**Comment by pedroprieto** [comment]
¿Puedes ser algo más concreto?

**Comment by pedroprieto** [comment]
Quiero decir, no sé cuál es tu demanda... ¿Puedes mostrar un `<div>` con algún dato del gasto?

**Comment by HiginioUrbano** [comment]
Si claro.

Estoy intentando crear la función mostraGastoWeb con los div y eso, pero no
sé muy bien como hacerlo como lo pones en el ejemplo, viendo la
videotutoria y los apuntes he sacado un par de cosas que creo que están más
o menos bien, pero no sé cómo completar la función

**Comment by pedroprieto** [comment]
Es una función que recibe un gasto (no el array). A partir de ahí, tiene que crear varios nodos HTML, cada uno con el dato del gasto correspondiente: https://es.javascript.info/modifying-document

Empieza a hacerla y observa el HTML que vas generando con el inspector del navegador. En principio trata de mostrar solo la descripción y luego vas añadiendo cosas.

Ánimo!

**Comment by HiginioUrbano** [comment]
Vale, le pego una vuelta de nuevo a ver si se me enciende la bombilla,
porque esa teoría me la he leído como 3 veces.
Con lo del inspector del navegador te refieres a lo del localhost y
liveserver?

**Comment by pedroprieto** [comment]
https://es.javascript.info/dom-nodes#vealo-usted-mismo

**Comment by HiginioUrbano** [comment]
Aquí, esta sección, no? Así compruebo si me está escribiendo cada una de
las líneas, cierto?

**Comment by pedroprieto** [comment]
Sí. Pulsa botón derecho sobre el HTML generado en el navegador y selecciona "Inspeccionar".
