### ISSUE TITLE
Duda mostrarGastoWeb

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#6]
@pedroprieto

He conseguido que al menos el programa me "pinte" los datos correctos en el html, pero me los pinta todos seguidos y sin limpieza, pero no se como hacer el resto, es todo lo que he podido hacer. Tampoco se como hacer lo del span que pides para las etiquetas, se que se haría más o menos como el div, pero cuando lo intento el programa deja de reconocerme todo.

Tampoco se como debo emplear en la funcion el idElemento, sería como hago en mostrarDato? Si me dieses algo de luz te lo agradecería, porque en cuanto saque esto creo que ya puedo casi terminar la practica...

**Comment by pedroprieto** [comment]
Tienes que ir creando elementos con https://es.javascript.info/modifying-document#creando-un-elemento. Puedes ir guardándolos en distintas variables, como has hecho aquí:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/948b59517b37d2b04cc2343f4b6ad577fbb8be3d/js/gestionPresupuestoWeb.js#L11

Vas creando los textos mediante https://es.javascript.info/modifying-document#metodos-de-insercion

Y vas añadiendo los nodos hijos al nodo padre mediante https://es.javascript.info/modifying-document#metodos-de-insercion también.

Los `span` se crean igual que los `div`, cambiando `"div"` por `"span"`: https://es.javascript.info/modifying-document#creando-un-elemento

El parámetro `idElemento` de la función `mostrarGastoWeb` indica el nombre del nodo donde debes crear el `div.gasto` que crees. En lugar de añadir el `div.gasto` directamente al documento, como haces aquí:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/948b59517b37d2b04cc2343f4b6ad577fbb8be3d/js/gestionPresupuestoWeb.js#L26

Debes añadirlo al elemento indicado con `idElemento`:
```js
var raiz = document.getElementById(idElemento);
raiz.append(div);    
```

De esta manera, cuando llames a la función `mostrarGastoWeb("listado-gastos-completo", gasto)` los `div` que crees se añadirán dentro del `div#listado-gastos-completo`.

Un saludo!

**Comment by HiginioUrbano** [comment]
Simplemente cambiando lo de raiz me ha servido, era ese paso el que me
faltaba, lo unico que tengo sin hacer ahora es lo de etiquetas que aun
tengo la duda, el span se crearlo, lo que no tengo claro es como hacer para
incluir esa etiqueta dentro del append, o no es necesario? No se si me
estoy explicando bien.

**Comment by HiginioUrbano** [comment]
DEntro del append no, queria decir dentro del div

**Comment by HiginioUrbano** [comment]
Vale ya se cual es mi error, lo que se pretende es que creemos un div con
clase gasto otros div con clase gasto descripcion, etc. En cambio yo estoy
creando un solo div gasto con todos los datos dentro sin dividirlos, pero
no se como crear un div y dentro de ese div volver a crear 6 div mas con
sus respectivas clases, porque cuando lo hago como estoy intentando me lo
mete todo en el ulitmo div.classname que creo, se puede hacer con append o
hay que usar otra?

**Comment by HiginioUrbano** [comment]
Asi serviría, no? En el html me da el resultado esperado:

        let div = document.createElement('div');
        let div1 = document.createElement('div');
        let div2 = document.createElement('div');
        let div3 = document.createElement('div');


        let span = document.createElement('span');
        div.className = "gasto";

        div1.className ="gasto-descripcion";
        div1.append(gasto.descripcion);

        div2.className ="gasto-fecha";
        div1.append(gasto.fecha);

        div3.className ="gasto-valor";
        div3.append(gasto.valor);



        div.append(div1);
        div.append(div2);
        div.append(div3);

**Comment by pedroprieto** [comment]
Puedes utilizar `append` sobre un elemento:
- Existente en el HTML, buscándolo con `getElementById` 
- Nuevo, creado desde JavaScript con `createElement`

Por tanto, puedes crear un elemento `div` que utilizarás como base (gasto); a continuación, crear varios `div` adicionales (descripción, valor, etc.) y añadirlos a ese primer `div` base; seguidamente, crear varios elementos `span` y añadirlos a uno de los `div` creados anteriormente (el que contenga las etiquetas); y por último, añadir el `div` base al elemento identificado con `id` de la función `mostrarGasto` (que será `listado-gastos-completo` o los correspondientes de filtrado; previamente lo tienes que haber localizado con `getElementById`).

**Comment by pedroprieto** [comment]
>  div1.append(gasto.fecha);

Sí. Aunque tienes una errata en el segundo.

**Comment by HiginioUrbano** [comment]
Que errata? Es que ya he conseguido que me pase los test

**Comment by pedroprieto** [comment]
![imagen](https://user-images.githubusercontent.com/7632447/140508185-60ccc7f5-0e48-4ba0-8be0-c6d3744e578d.png)

**Comment by HiginioUrbano** [comment]
Tienes razon, pues me estaba pasando los test bien igualmente.
