### ISSUE TITLE
Filtrar Gastos

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#7]
@pedroprieto No se como pasar la funcion filtrar gastos, he probado haciendolo con bucle y sin el bucle y no me funciona. No se me ocurre que mas hacer para filtrar los gastos a través de la fecha

**Comment by pedroprieto** [comment]
Si sabes mostrar todos los gastos también sabes mostrar los filtrados. Ten en cuenta que `filtrarGastos` devuelve un array. Es lo mismo que con `listarGastos`. Primero filtras y luego iteras el array resultante: para cada gasto llamas a la función de `mostrarGastoWeb`.

**Comment by HiginioUrbano** [comment]
Ya, si eso es lo que estoy intentacion hacer, pero el test me dice que
gastos is not irable, aunque no tenga definida ninguna variable gastos

**Comment by HiginioUrbano** [comment]
Sigo con este problema después de tnatos días... incluso he copiado la
función de un compañero que hablé con el con la desesperación para ver si
era el fallo y me seguía tirando error, porque creo que la lógica de la
función es correcta... no se que más hacer.

**Comment by pedroprieto** [comment]
Buenas,

A ver, tienes que revisar el código tranquilamente. El problema es fácil de detectar:

En primer lugar, la función `mostrarGastoWeb` tal como la has hecho, acepta un parámetro `gastos` que es un array. Dentro de la función iteras dicho array y muestras cada gasto:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/gestionPresupuestoWeb.js#L8
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/gestionPresupuestoWeb.js#L9

Lógicamente, en la llamada a la función pasas como parámetro el array de gastos:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/generarDatosEstaticos.js#L30

Sin embargo, en la siguiente llamada con los gastos filtrados, iteras __fuera de la función__ y le pasas a `mostrarGastoWeb` un elemento en lugar de un array:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/generarDatosEstaticos.js#L33
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/generarDatosEstaticos.js#L35

Y encima tienes un error de sintaxis, porque la variable de iteración es `gastoFiltrado` y la que utilizas dentro es `gastosFiltrado`.

Por tanto, los gastos filtrados no se te mostrarán. Lo que tienes que hacer es llamar a `mostrarGastoWeb` pasándole como parámetro el array `gastosFiltrados` y quitar el bucle siguiente:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/generarDatosEstaticos.js#L33

Todo esto son fallos relativamente sencillos que tienes que ser capaz de detectar por ti mismo. Creo que te agobia demasiado hacer el trabajo lo antes posible: párate un rato, o incluso borra (o comenta) lo que no te funcione y trata de hacerlo de nuevo desde el principio. Por supuesto que habrá veces que te costará encontrar el fallo, pero ten paciencia y procede metódicamente: haz pruebas con `console.log` para mostrar las variables o parámetros de la función que estés pasando, utiliza las herramientas de inspección del navegador, etc.

Dicho todo esto, en realidad el enunciado pide que `mostrarGastoWeb` tome como parámetro __un único gasto__, no un array. Por tanto, el método que has seguido para mostrar los gastos filtrados (poner el bucle en `generarDatosEstaticos.js`) es el correcto (si corriges el error de la variable que te he comentado, claro :wink:). Eso sí, para que funcione correctamente deberás quitar el bucle de `gestionPresupuestoWeb.js`:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/01dac107cd0b23e56a3fa71b036f906c52fab6fd/js/gestionPresupuestoWeb.js#L9
Y renombrar el parámetro para que se llame `gasto` en lugar de `gastos`.

Un saludo, ánimo y paciencia, que no hace falta que corras tanto!!!

**Comment by HiginioUrbano** [comment]
Claro Que intento ir rápido... Voy ya con una semana de retraso y esta
semana seguro que subes otra actividad y más faena acumulada... No me gusta
no ir al día.

Por cierto, he realizado los cambios que me has dicho y me sigue saltando
un error, ahora me dice que no se puede leer el null de append... He
actualizado mi codigo en mi repositorio por si le quieres echar un vistazo,
estoy desesperado ya.

**Comment by pedroprieto** [comment]
Si no digo que no vayas rápido... Pero a veces ir rápido no te lleva a ningún sitio, nada más que a quedarte parado. 

Como ahora, por ejemplo. ¿Qué tipo de error tienes? 
![imagen](https://user-images.githubusercontent.com/7632447/140718713-ba2da4a9-5eaa-4e58-92a6-24b9fbd68c42.png)

Parece ser que haces `append` sobre un elemento nulo. Si ejecutas la web en el navegador y muestras la consola:
![imagen](https://user-images.githubusercontent.com/7632447/140718824-40bf1e6e-92d7-4ca8-90b0-a6903a593388.png)

Parece ser que `raiz` es `null`. `raiz` en tu código es:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/b6d9fc24df7ebf9909688fe5936f612964a41676/js/gestionPresupuestoWeb.js#L46

Por tanto, parece que estás pasando un `idElemento` que no existe. Tras revisar el código donde llamas a esa función, en `generarDatosEstaticos.js` descubres que:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/b6d9fc24df7ebf9909688fe5936f612964a41676/js/generarDatosEstaticos.js#L41

Por tanto, parece que `listado-gastos-filtrados-1` no es un `id` válido. Con esto, vas al html y descubres que:
https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/b6d9fc24df7ebf9909688fe5936f612964a41676/interaccionHTML.html#L26

Te sobra una `s` :tada: 

Ánimo y paciencia!!!

**Comment by HiginioUrbano** [comment]
TIenes razón, lo siento Pedro, esta práctica en concreto me ha agotado
mentalmente y me está costando verlo todo el triple que de normal.
Intentaré prestar más atención aún.

**Comment by pedroprieto** [comment]
Nada, hombre. Tranquilo y pregunta lo que haga falta!! Para eso estoy!! :wink: 

Con respecto a lo de la rapidez, solo trataba de transmitirte calma, igual no lo he conseguido del todo. Vas bien en las entregas, no vas retrasado en exceso. Ten en cuenta que en las tutorías de cada semana comento los detalles más complicados y los problemas más habituales de las prácticas de la semana anterior. Si te esperas a la grabación de la tutoría la práctica te resultará más sencilla (o eso espero :wink: )

Ánimo pues!!
