### ISSUE TITLE
Duda nueva práctica

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#8]
@pedroprieto He estado realizando la práctica siguiendo lo que pides y he sacado este código. No se si estoy yendo muy desencaminado o no. El código no funciona, solo me salen los botones actualizar presupuesto y anyadir gasto, aún no me he mareado en el porqué ya que me he centrado en desarrollar el groso del código. ¿Me podrías decir si voy bien encaminado con la idea del código?

Y si de paso me encaminas un poco del porque solo me salen los dos botones en los test también me ayudaría. Muchas gracias y un saludo.

**Comment by pedroprieto** [comment]
Buenas,

¿Puedes ser un poco más concreto? ¿Qué quieres que mire exactamente? ¿El botón de añadir, los de editar y borrar de los gastos,...? ¿Tienes dudas con el manejador de evento?

**Comment by HiginioUrbano** [comment]
Buenas Pedro,

He realizado una idea general de todas las funciones, mi "duda", es si voy
en la orientación correcta. Se que tengo errores que pulir todavía uno de
ellos me lo comentaste en un correo anterior con los botones que no debo
poner funciones. Al margen de esos botones, los manejadores de eventos y
las posteriores funciones donde los uso, están (más o menos) bien
planteados o me estoy alejando mucho de la idea correcta?

**Comment by pedroprieto** [comment]
En principio vas bien: los botones están creados donde corresponde. Pero hasta que no lo tengas todo no se sabrá :man_shrugging:

**Comment by HiginioUrbano** [comment]
Si si, esa era mi pregunta. Hoy estoy dedicando tiempo a otras asignaturas,
pero mañana me pongo a tope con esto y lo dejo todo como debe estar.
Teniendo claro que el concepto va bien ya se más o menos como debo
terminarlo. Muchas gracias por todo. Un saludo

**Comment by pedroprieto** [comment]
:+1:
