### ISSUE TITLE
Codigo no funcional

### ISSUE THREAD

**Issue by HiginioUrbano** [HiginioUrbano/practica_dwec_gestor_presupuesto#9]
@pedroprieto He probado varias cosas como me has propuesto en el correo y nada. Lo tengo lanzado en el navegador, por consola y nada. El problema es que en el navegador solo me están saliendo los dos botones actualizarPresupuesto y anaydir gasto y nada más. Me meto a inspeccionar y aparecen las etiquetas div etc, pero vacías. Hay algo que está haciendo conflicto, pero he repasado como 5 veces en código y no veo donde está, llevo desde las 9 con esto y no  he sido capaz. Hay algo mal, pero no se donde.

**Comment by pedroprieto** [comment]
![imagen](https://user-images.githubusercontent.com/7632447/141288677-cfddc25d-2f6c-4c54-910a-1af0f45bc185.png)

https://github.com/HiginioUrbano/practica_dwec_gestor_presupuesto/blob/9eddd111114e2de32efd43d96902d95be38d2cb3/js/gestionPresupuestoWeb.js#L1

Por favor, mira la consola al hacer las pruebas.

Un saludo!!

**Comment by HiginioUrbano** [comment]
A mi es que eso en con los test de cypress no me sale.

Al margen de eso, llámame tonto, pero con eso, no se donde está exactamente
el error :(

**Comment by pedroprieto** [comment]
Es que es la consola del navegador. Por eso te digo que debes utilizar la consola del navegador al cargar el archivo mediante la extensión `Live Server` de Visual Studio Code. Cuando la página se esté ejecutando, pulsas `F12` para acceder. Ahí verás los errores que se producen.

> Al margen de eso, llámame tonto, pero con eso, no se donde está exactamente
el error :(

Te falta el `.js` final del nombre de archivo.

**Comment by HiginioUrbano** [comment]
Lo que no entiendo es porque eso no me estaba dando conflicto antes... O
solo da conflicto en el momento que tiene que interactuar directamente con
el html?

**Comment by pedroprieto** [comment]
Porque antes (práctica anterior) esa importación no la tenías puesta, ya que ese archivo no tenía que trabajar con el otro (lo hacía solo `generarDatosEstaticos.js`). Ahora si que lo necesita, ya que vamos a integrar la funcionalidad de la aplicación con la parte de gestión de eventos.

**Comment by HiginioUrbano** [comment]
Vale vale, comprendo. Esa parte del código es como que ya la había dado por
correcta y no la había revisado.
